spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  application:
      name: microservice-zuul-gateway
server:
  port: 9527
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true
zuul:
  routes:
    hotdogEmployee.serviceId: employee-provider
    hotdogEmployee.path: /employee/**
    hotdogProduct.serviceId: product-service-8002
    hotdogProduct.path: /product/**
    hotdogCommon.serviceId: product-service-8002
    hotdogCommon.path: /common/** # 匹配 /xxx开头的请求映射到user-provider服务上
  ignored-services: "*" #user-provider #忽略直接使用服务名访问  *忽略所有的
  prefix: /hotdog   # 访问前缀

---
spring:
  profiles: test
  application:
      name: microservice-zuul-gateway-test
server:
  port: 9528
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true
zuul:
  routes:
    hotdogEmployee.serviceId: employee-provider
    hotdogEmployee.path: /employee/** 
    hotdogProduct.serviceId: product-service-8002
    hotdogProduct.path: /product/**       # 匹配 /xxx开头的请求映射到user-provider服务上
  ignored-services: "*" #user-provider #忽略直接使用服务名访问  *忽略所有的
  prefix: /hotdog   # 访问前缀
