spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  application:
    name: product-provider
  datasource:  #数据库的配置
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hotdog?useUnicode=true&characterEncoding=UTF-8  #防止中文乱码
    username: root
    password: 1234
server:
  port: 8002
eureka:
  client:
    service-url:
      defaultZone: http://www.eureka-7001.com:7001/eureka  #告诉服务提供者要把服务注册到哪儿 #单机环境
  instance:
    prefer-ip-address: true #显示客户端真实ip

---
spring:
  profiles: test
  application:
    name: product-provider-test
server:
  port: 8003
eureka:
  client:
    service-url:
      defaultZone: http://www.eureka-7001.com:7001/eureka  #告诉服务提供者要把服务注册到哪儿 #单机环境
  instance:
    prefer-ip-address: true #显示客户端真实ip
