
spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  application:
    name: common-provider
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 127.0.0.1:9300 
server:
  port: 8003
  max-http-header-size: 4048576
eureka:
  client:
    service-url:
      defaultZone: http://www.eureka-7001.com:7001/eureka  #告诉服务提供者要把服务注册到哪儿 #单机环境
  instance:
    prefer-ip-address: true #显示客户端真实ip
---
spring:
  profiles: test
  application:
    name: product-provider-test
server:
  port: 8003
eureka:
  client:
    service-url:
      defaultZone: http://www.eureka-7001.com:7001/eureka  #告诉服务提供者要把服务注册到哪儿 #单机环境
  instance:
    prefer-ip-address: true #显示客户端真实ip
